package com.agilerules.ecommerce.agilekart;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(875ab29e6a3452ad939e8c13f720a5b9)
 */
@org.kie.api.definition.type.Label(value = "OrderObject")
public class OrderObject extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "address")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String address;
    
    @org.kie.api.definition.type.Label(value = "email")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String email;
    
    @org.kie.api.definition.type.Label(value = "name")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String name;
    
    @org.kie.api.definition.type.Label(value = "orderId")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String orderId;
    
    @org.kie.api.definition.type.Label(value = "products")
    @org.kie.api.definition.type.Position(value = 5)
    private java.util.List<com.agilerules.ecommerce.agilekart.ProductObject> products;
    
    @org.kie.api.definition.type.Label(value = "status")
    @org.kie.api.definition.type.Position(value = 1)
    private boolean status;

    public OrderObject() {
    }

    public OrderObject(java.lang.String orderId, boolean status, java.lang.String name, java.lang.String email, java.lang.String address, java.util.List<com.agilerules.ecommerce.agilekart.ProductObject> products) {
        this.orderId = orderId;
        this.status = status;
        this.name = name;
        this.email = email;
        this.address = address;
        this.products = products;
    }


    
    public java.lang.String getAddress() {
        return this.address;
    }

    public void setAddress(java.lang.String address) {
        this.address = address;
    }
    
    public java.lang.String getEmail() {
        return this.email;
    }

    public void setEmail(java.lang.String email) {
        this.email = email;
    }
    
    public java.lang.String getName() {
        return this.name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getOrderId() {
        return this.orderId;
    }

    public void setOrderId(java.lang.String orderId) {
        this.orderId = orderId;
    }
    
    public java.util.List<com.agilerules.ecommerce.agilekart.ProductObject> getProducts() {
        return this.products;
    }

    public void setProducts(java.util.List<com.agilerules.ecommerce.agilekart.ProductObject> products) {
        this.products = products;
    }
    
    public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }
}