package com.agilerules.ecommerce.agilekart;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(5c87d7a03fd5692fa33919877b1457c7)
 */
@org.kie.api.definition.type.Label(value = "ProductObject")
public class ProductObject  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "prodctPrice")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String prodctPrice;
    
    @org.kie.api.definition.type.Label(value = "productName")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String productName;

    public ProductObject() {
    }

    public ProductObject(java.lang.String productName, java.lang.String prodctPrice) {
        this.productName = productName;
        this.prodctPrice = prodctPrice;
    }


    
    public java.lang.String getProdctPrice() {
        return this.prodctPrice;
    }

    public void setProdctPrice(java.lang.String prodctPrice) {
        this.prodctPrice = prodctPrice;
    }
    
    public java.lang.String getProductName() {
        return this.productName;
    }

    public void setProductName(java.lang.String productName) {
        this.productName = productName;
    }
}